-----------------------------------------------------------
-- Szinkronfeliratok
-----------------------------------------------------------
-- Keszitette: The Sweet Little 16-bit (tsl16b@freemail.hu)
-----------------------------------------------------------
-- forgottenspiral
-- v0.0
-----------------------------------------------------------

--id														= texture
tips_icons =
{
	zat_stalker_actor_name									=	"ui_inGame2_Hero",
	zat_a2_stalker_barmen_name							=	"ui_inGame2_Boroda",
}

--id																											=	{showtime}
mob_snds =
{
}

--id																														=	{showtime}
npc_snds =
{
	characters_voice_scenario_jupiter_jup_a6_duty_leader_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_duty_leader_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_a6_duty_leader_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_duty_leader_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_a6_freedom_leader_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_freedom_leader_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_a6_freedom_leader_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_freedom_leader_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_barmen_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_barmen_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_barmen_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_barmen_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_medik_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_medik_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_medik_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_a6_stalker_medik_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_b15_zulus_greeting	=	{3},
	characters_voice_scenario_jupiter_jup_b1_stalkers_greeting	=	{3},
	characters_voice_scenario_jupiter_jup_b217_stalker_tech_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_b217_stalker_tech_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_b217_stalker_tech_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_b217_stalker_tech_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_b220_trapper_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_b220_trapper_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_b220_trapper_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_b220_trapper_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_biochemist_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_biochemist_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_biochemist_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_biochemist_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_medic_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_medic_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_medic_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_medic_greeting_2	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_nuclear_physicist_farewell_1	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_nuclear_physicist_farewell_2	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_nuclear_physicist_greeting_1	=	{3},
	characters_voice_scenario_jupiter_jup_b6_scientist_nuclear_physicist_greeting_2	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_farewell_1	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_farewell_2	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_farewell_angry_1	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_farewell_angry_2	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_greeting_1	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_greeting_2	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_greeting_angry_1	=	{3},
	characters_voice_scenario_zaton_zat_a2_stalker_barmen_greeting_angry_2	=	{3},
	characters_voice_scenario_zaton_zat_b18_noah_greetings_1	=	{3},
	characters_voice_scenario_zaton_zat_b18_noah_greetings_2	=	{3},
	characters_voice_scenario_zaton_zat_b18_noah_greetings_3	=	{3},
	characters_voice_scenario_zaton_zat_b215_stalker_guide_farewell_1	=	{3},
	characters_voice_scenario_zaton_zat_b215_stalker_guide_farewell_2	=	{3},
	characters_voice_scenario_zaton_zat_b215_stalker_guide_greeting_1	=	{3},
	characters_voice_scenario_zaton_zat_b215_stalker_guide_greeting_2	=	{3},
	characters_voice_scenario_zaton_zat_b22_stalker_medic_farewell_1	=	{3},
	characters_voice_scenario_zaton_zat_b22_stalker_medic_farewell_2	=	{3},
	characters_voice_scenario_zaton_zat_b22_stalker_medic_greeting_1	=	{3},
	characters_voice_scenario_zaton_zat_b22_stalker_medic_greeting_2	=	{3},
	characters_voice_scenario_zaton_zat_b30_owl_stalker_trader_farewell_1	=	{3},
	characters_voice_scenario_zaton_zat_b30_owl_stalker_trader_farewell_2	=	{3},
	characters_voice_scenario_zaton_zat_b30_owl_stalker_trader_greeting_1	=	{3},
	characters_voice_scenario_zaton_zat_b30_owl_stalker_trader_greeting_2	=	{3},
	characters_voice_scenario_zaton_zat_b33_stalker_snag_greeting_gun	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_1	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_2	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_3	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_order_not_ready_1	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_order_not_ready_2	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_order_not_ready_3	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_order_ready_1	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_order_ready_2	=	{3},
	characters_voice_scenario_zaton_zat_b51_stalker_nimble_greeting_order_ready_3	=	{3},
	characters_voice_scenario_zaton_zat_b7_bandit_boss_sultan_farewell_1	=	{3},
	characters_voice_scenario_zaton_zat_b7_bandit_boss_sultan_farewell_2	=	{3},
	characters_voice_scenario_zaton_zat_b7_bandit_boss_sultan_greeting_1	=	{3},
	characters_voice_scenario_zaton_zat_b7_bandit_boss_sultan_greeting_2	=	{3},
}

--id																										=	{showtime, sender}
actor_snds =
{
}

--id																												=	{color, showtime, [distance, or sender]}
obj_snds =
{
	characters_voice_scenario_jupiter_jup_a6_base_megaphone_1	=	{2, 5, 1000},
	characters_voice_scenario_jupiter_jup_a6_base_megaphone_2	=	{2, 5, 1000},
	characters_voice_scenario_jupiter_jup_a6_base_megaphone_3	=	{2, 5, 1000},
	characters_voice_scenario_jupiter_jup_b41_bunker_megaphone_1	=	{2, 5, 1000},
	characters_voice_scenario_jupiter_jup_b41_bunker_megaphone_2	=	{2, 5, 1000},
	characters_voice_scenario_jupiter_jup_b41_bunker_megaphone_3	=	{2, 5, 1000},
	characters_voice_scenario_pripyat_pri_a16_base_megaphone_1	=	{2, 5, 1000},
	characters_voice_scenario_pripyat_pri_a16_base_megaphone_2	=	{2, 5, 1000},
	characters_voice_scenario_pripyat_pri_a16_base_megaphone_3	=	{2, 5, 1000},
	characters_voice_scenario_zaton_zat_a2_base_megaphone_1	=	{2, 5, 1000},
	characters_voice_scenario_zaton_zat_a2_base_megaphone_2	=	{2, 5, 1000},
	characters_voice_scenario_zaton_zat_a2_base_megaphone_3	=	{2, 5, 1000},
}

-- p:string
function cc_display_mobsnd(p)
	local cc_id = string.gsub(p, "\\", "_")
	local cc_value = mob_snds[cc_id]
	if cc_value then
		cc_display_subs(cc_id, 1, cc_value[1]) -- only for Sid and Forester
	end
end

-- cc_id:string
function cc_display_npcsnd(cc_id)
	local cc_value = npc_snds[cc_id]
	if cc_value then
		cc_display_subs("cc_" .. cc_id, 1, cc_value[1]) -- only for greetings and farewells
	end
end

-- p:string, obj:userdata
function cc_display_sndpath(p, obj)
	local cc_id = string.gsub(p, "\\", "_")
	local cc_value = actor_snds[cc_id]
	if cc_value then
		cc_send_tip(cc_id, cc_value[1]*1000, cc_value[2]) -- pda message
	else
		cc_value = obj_snds[cc_id]
		if cc_value then
			if cc_value[1] == -1 then
				cc_send_tip(cc_id, cc_value[2]*1000, cc_value[3]) -- pda message
			elseif cc_value[1] >= 1 and obj ~= nil then
				local dist = obj:position():distance_to_sqr(db.actor:position())
				if dist <= cc_value[3] then
					cc_display_subs(cc_id, cc_value[1], cc_value[2]) -- megafon and soldier
				end
			end
		end
	end
end

-- cc_id:string, color:number, showtime:number
function cc_display_subs(cc_id, color, showtime)
	if color == nil or showtime == nil then return end
	if db.actor:is_talking() then return end
	if db.cc_npc == true then
		local time_now = time_global() / 1000
		local time_ccend = time_now + showtime

		local tmpl = "closecaption_" .. color
		local hud = get_hud()
		hud:AddCustomStatic(tmpl, true)
		hud:GetCustomStatic(tmpl):wnd():SetTextST(game.translate_string(cc_id))
		hud:GetCustomStatic(tmpl).m_endTime = time_ccend
	elseif db.cc_npc == nil then
		read_cc_ini()
		if db.cc_npc ~= nil then
			cc_display_subs(cc_id, color, showtime)
		end
	end
end

-- news_id:string, showtime:number, sender:string
function cc_send_tip(news_id, showtime, sender)
	if showtime == nil or sender == nil then return end
	if db.cc_npc == true then

		local texture = tips_icons[sender]
		local news_caption = game.translate_string("st_tip") .. ":"
		local news_text = game.translate_string(news_id)

		db.actor:give_game_news(news_caption, news_text, texture, 0, showtime, 1)
	elseif db.cc_npc == nil then
		read_cc_ini()
		if db.cc_npc ~= nil then
			cc_send_tip(news_id, showtime, sender)
		end
	end
end

function read_cc_ini()
	-------- read values from the closecaption.ltx file
	-------- commented lines used as reference if they need to be used in the future
	local cc = "closecaption"
	-- local p_igm, cc_igm, cc_npc, cc_icc, cc_nip = true, false, false, false, false
	local cc_npc = false
	cc_npc = load_variable("cc_npc", 0)
	if cc_npc == 0 then
		local ini = ini_file("misc\\closecaption.ltx")
		if ini:section_exist(cc) then
			--[[
			if ini:line_exist(cc, "play_igm") then
       				p_igm = ini:r_bool(cc, "play_igm")
			end
			 ]]
			--[[
 			if ini:line_exist(cc, "cc_ingame_video") then
				cc_igm = ini:r_bool(cc, "cc_ingame_video")
			end
			 ]]
			if ini:line_exist(cc, "cc_ingame_npc") then
				cc_npc = ini:r_bool(cc, "cc_ingame_npc")
			end
			--[[
 			if ini:line_exist(cc, "cc_ingame_cc") then
				cc_icc = ini:r_bool(cc, "cc_ingame_cc")
			end
			 ]]
			--[[
			if ini:line_exist(cc, "cc_add_new_info") then
				cc_nip = ini:r_bool(cc, "cc_add_new_info")
			end
			 ]]
			--[[
			if ini:line_exist(cc, "cc_video_player") then
				cc_vpl = ini:r_bool(cc, "cc_video_player")
			end
			 ]]
		end
		-- db.p_igm = p_igm
		-- db.cc_igm = cc_igm
		db.cc_npc = cc_npc
		-- db.cc_icc = cc_icc
		-- db.cc_nip = cc_nip
		-- save_variable("cc_nip", cc_nip)
		-- save_variable("cc_icc", cc_icc)
		save_variable("cc_npc", cc_npc)
		-- save_variable("cc_igm", cc_igm)
		-- save_variable("p_igm", p_igm)
	else
		-- cc_nip = load_variable("cc_nip", cc_nip)
		-- cc_icc = load_variable("cc_icc", cc_icc)
		-- cc_igm = load_variable("cc_igm", cc_igm)
		-- p_igm = load_variable("p_igm", p_igm)
		-- db.p_igm = p_igm
		-- db.cc_igm = cc_igm
		db.cc_npc = cc_npc
		-- db.cc_icc = cc_icc
		-- db.cc_nip = cc_nip
	end
end

-- code portions from the excellent AMK mod --
function save_variable(variable_name, value)
  xr_logic.pstor_store(db.actor, variable_name, value)
end

function load_variable(variable_name, value_if_not_found)
  return xr_logic.pstor_retrieve(db.actor, variable_name, value_if_not_found)
end

function del_variable(variable_name)
  if db.storage[db.actor:id()].pstor[variable_name] then
    db.storage[db.actor:id()].pstor[variable_name] = nil
  end
end
